# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ramadan\Desktop\Shazam\Main\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 709)
        MainWindow.setMinimumSize(QtCore.QSize(489, 709))
        MainWindow.setMaximumSize(QtCore.QSize(489, 709))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(-1, 40, -1, 40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.load_songs = QtWidgets.QPushButton(self.centralwidget)
        self.load_songs.setObjectName("load_songs")
        self.verticalLayout_3.addWidget(self.load_songs)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.song_1_percentage = QtWidgets.QSlider(self.centralwidget)
        self.song_1_percentage.setEnabled(False)
        self.song_1_percentage.setMaximum(100)
        self.song_1_percentage.setProperty("value", 100)
        self.song_1_percentage.setOrientation(QtCore.Qt.Horizontal)
        self.song_1_percentage.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.song_1_percentage.setObjectName("song_1_percentage")
        self.verticalLayout.addWidget(self.song_1_percentage)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.shazam = QtWidgets.QPushButton(self.centralwidget)
        self.shazam.setEnabled(False)
        self.shazam.setObjectName("shazam")
        self.verticalLayout_3.addWidget(self.shazam)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdd_to_DB = QtWidgets.QMenu(self.menubar)
        self.menuAdd_to_DB.setObjectName("menuAdd_to_DB")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_New_Songs_to_DB = QtWidgets.QAction(MainWindow)
        self.actionAdd_New_Songs_to_DB.setObjectName("actionAdd_New_Songs_to_DB")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionExit)
        self.menuAdd_to_DB.addAction(self.actionAdd_New_Songs_to_DB)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdd_to_DB.menuAction())

        self.retranslateUi(MainWindow)
        self.song_1_percentage.valueChanged['int'].connect(self.progressBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_songs.setText(_translate("MainWindow", "Load Songs"))
        self.shazam.setText(_translate("MainWindow", "Tab To Shazam"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAdd_to_DB.setTitle(_translate("MainWindow", "Configure"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAdd_New_Songs_to_DB.setText(_translate("MainWindow", "Add New Songs to DB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
