# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ramadan\Desktop\Shazam\Main\Output.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_matches(object):
    def setupUi(self, matches):
        matches.setObjectName("matches")
        matches.resize(489, 709)
        matches.setMinimumSize(QtCore.QSize(489, 709))
        matches.setMaximumSize(QtCore.QSize(489, 709))
        self.verticalLayout = QtWidgets.QVBoxLayout(matches)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(matches)
        self.label.setMinimumSize(QtCore.QSize(441, 131))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.song_info = QtWidgets.QLabel(matches)
        self.song_info.setMinimumSize(QtCore.QSize(451, 91))
        self.song_info.setObjectName("song_info")
        self.verticalLayout.addWidget(self.song_info)
        self.song_matches = QtWidgets.QTableWidget(matches)
        self.song_matches.setMinimumSize(QtCore.QSize(311, 261))
        self.song_matches.setObjectName("song_matches")
        self.song_matches.setColumnCount(2)
        self.song_matches.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.song_matches.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.song_matches.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.song_matches.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.song_matches.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.song_matches.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.song_matches.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.song_matches.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.song_matches)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.back = QtWidgets.QPushButton(matches)
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(matches)
        QtCore.QMetaObject.connectSlotsByName(matches)

    def retranslateUi(self, matches):
        _translate = QtCore.QCoreApplication.translate
        matches.setWindowTitle(_translate("matches", "Matches"))
        self.label.setText(_translate("matches", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">The Song Might Be</span></p></body></html>"))
        self.song_info.setText(_translate("matches", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Song Name</span></p><p align=\"center\"><span style=\" font-weight:600;\">by: Author Name</span></p></body></html>"))
        item = self.song_matches.horizontalHeaderItem(0)
        item.setText(_translate("matches", "Song Name"))
        item = self.song_matches.horizontalHeaderItem(1)
        item.setText(_translate("matches", "CL"))
        self.back.setText(_translate("matches", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    matches = QtWidgets.QWidget()
    ui = Ui_matches()
    ui.setupUi(matches)
    matches.show()
    sys.exit(app.exec_())
